# Generated by Django 4.0.3 on 2022-04-08 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='cat',
            new_name='cat_id',
        ),
    ]
